apiVersion: 1
groups:
    - orgId: 1
      name: bike-model-alerts
      folder: MLOps Alerts
      interval: 1m
      rules:
        - uid: ffldqujsb00zkd
          title: ApiPredictLatencyHigh
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                expr: |
                    api_request_duration_seconds_sum{endpoint="/predict", method="POST"} / api_request_duration_seconds_count{endpoint="/predict", method="POST"}
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            description: |
                La latence moyenne de l'endpoint /predict dépasse 0.5s depuis plus de 5 minutes.
            summary: Latence /predict trop élevée (> 0.5s)
          labels:
            service: bike-api
            severity: critical
            team: mlops
          isPaused: false
        - uid: drift-detected-alert
          title: DriftDetected
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                expr: evidently_drift_detected
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          annotations:
            description: |
                Evidently a détecté une dérive de distribution entre les données courantes et la référence de janvier 2011.
            summary: Dérive de données détectée
          labels:
            service: bike-api
            severity: critical
            team: mlops
          isPaused: false
        - uid: rmse-too-high-alert
          title: RMSETooHigh
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                expr: model_rmse_score
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          annotations:
            description: |
                Le RMSE du modèle Bike Sharing dépasse le seuil critique de 60.
            summary: RMSE du modèle trop élevé (> 60)
          labels:
            service: bike-api
            severity: critical
            team: mlops
          isPaused: false
    - orgId: 1
      name: infrastructure-alerts
      folder: MLOps Alerts
      interval: 1m
      rules:
        - uid: cpu-usage-high-alert
          title: CpuUsageHigh
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                expr: |
                    100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            description: |
                L'utilisation CPU dépasse 90% — risque de dégradation des prédictions.
            summary: CPU > 90% depuis 5 minutes
          labels:
            service: infrastructure
            severity: critical
            team: mlops
          isPaused: false
        - uid: memory-usage-high-alert
          title: MemoryUsageHigh
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                expr: |
                    (node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 2m
          annotations:
            description: La mémoire disponible est critique — le modèle ou l'API risque d'être OOM-killed.
            summary: RAM > 80%
          labels:
            service: infrastructure
            severity: warning
            team: mlops
          isPaused: false
