apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy           # Grafana contacte Prometheus depuis le réseau Docker interne
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"         # intervalle de scrape, doit correspondre à prometheus.yml
      httpMethod: POST            # POST est plus efficace pour les longues requêtes PromQL